import Head from 'next/head';
import Image from 'next/image';
import Coins from '../components/Coins';
import SearchBar from '../components/SearchBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <SearchBar type='text' placeholder='Search' />
      <Coins />
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch(
    'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false'
  );
  const filteredCoins = await res.json();

  return {
    props: { filteredCoins },
  };
}
